#!/bin/bash

#SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
VERSION="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P | rev | cut -d / -f 1 | rev )"
#VERSION=$( echo $SCRIPTPATH | rev | cut -d / -f 1 | rev )

if [ "$1" == "--version" ]; then echo $VERSION; exit; fi
echo "Hello world!"
